
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dist 
          retention-days: 1
          name: web