name: deployment

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dist 
          retention-days: 1
          name: web
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: web 
          path: "dist/" 
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SOURCE: "dist/" 